#!/usr/bin/env node

/**
 * Generate TypeScript types from backend OpenAPI specification
 * 
 * This script:
 * 1. Fetches the OpenAPI spec from the running backend
 * 2. Generates TypeScript types using openapi-typescript
 * 3. Saves types to src/types/api-generated.ts
 * 
 * Usage:
 *   npm run generate-types
 * 
 * Requirements:
 *   - Backend must be running on NEXT_PUBLIC_API_URL
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000/api';
const OPENAPI_ENDPOINT = `${API_URL}/docs/openapi.json`;
const OUTPUT_FILE = path.join(__dirname, '../src/types/api-generated.ts');

async function generateTypes() {
  try {
    console.log('🔍 Fetching OpenAPI spec from:', OPENAPI_ENDPOINT);
    
    // Fetch OpenAPI spec
    const response = await fetch(OPENAPI_ENDPOINT);
    if (!response.ok) {
      throw new Error(`Failed to fetch OpenAPI spec: ${response.statusText}`);
    }
    
    const openApiSpec = await response.json();
    console.log('✅ OpenAPI spec fetched successfully');
    
    // Save spec for reference
    const specFile = path.join(__dirname, '../openapi-spec.json');
    fs.writeFileSync(specFile, JSON.stringify(openApiSpec, null, 2));
    console.log('📝 Saved OpenAPI spec to:', specFile);
    
    // Use openapi-typescript to generate types
    const { default: openapiTS } = await import('openapi-typescript');
    
    const types = await openapiTS(openApiSpec);
    
    // Add header comment
    const output = `/**
 * AUTO-GENERATED TypeScript types from backend OpenAPI specification
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * Generated: ${new Date().toISOString()}
 * Source: ${OPENAPI_ENDPOINT}
 * 
 * To regenerate: npm run generate-types
 */

${types}
`;
    
    // Ensure output directory exists
    const outputDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }
    
    // Write types file
    fs.writeFileSync(OUTPUT_FILE, output);
    console.log('✅ Types generated successfully:', OUTPUT_FILE);
    console.log('');
    console.log('🎉 Type generation complete!');
    console.log('   You can now import types from @/types/api-generated');
    
  } catch (error) {
    console.error('❌ Error generating types:', error.message);
    console.error('');
    console.error('Troubleshooting:');
    console.error('  1. Make sure the backend is running');
    console.error('  2. Check that NEXT_PUBLIC_API_URL is set correctly');
    console.error('  3. Verify the backend has an OpenAPI endpoint at /api/docs/openapi.json');
    process.exit(1);
  }
}

generateTypes();
